name: dask-cloudprovider-test
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - nomkl
  - pip
  # Dask
  - dask
  # testing / CI
  - flake8
  - ipywidgets
  - pytest
  - pytest-asyncio
  - black >=20.8b1
  - pyyaml
  # dask dependencies
  - cloudpickle
  - toolz
  - cytoolz
  - numpy
  - partd
  # distributed dependencies
  - click >=6.6
  - msgpack-python
  - psutil >=5.0
  - six
  - sortedcontainers !=2.0.0,!=2.0.1
  - tblib
  - tornado >=5
  - zict >=0.1.3
  # `event_loop_policy` change See https://github.com/dask/distributed/pull/4212
  - pytest-asyncio >=0.14.0
  - pytest-timeout
  - pip:
      - git+https://github.com/dask/dask.git@main
      - git+https://github.com/dask/distributed@main
